### ISSUE TITLE
type annotations required: cannot resolve `_: timely::progress::Timestamp`

### ISSUE THREAD

**Issue by florianre** [TimelyDataflow/differential-dataflow#103]
Hi, 
I am trying to just see how fast it takes to update the graph format being used: 
` timely::execute_from_args(std::env::args().skip(5), move |worker| {
   let index = worker.index();
   let peers = worker.peers();
   
let (edgeArray, graph) = worker.dataflow(|scope| {
    let (mut input, graph) = scope.new_collection();
    let mut v = Vec::<(u32, u32)>::new();
    let file = BufReader::new(File::open(filename.clone()).unwrap());

    for (count, readline) in file.lines().enumerate() {
        let line = readline.ok().expect("read error");
        if !line.starts_with('#') {
            let mut elts = line[..].split_whitespace();
            let src: u32 = elts.next().unwrap().parse().ok().expect("malformed src");
            let dst: u32 = elts.next().unwrap().parse().ok().expect("malformed dst");
                v.push((src, dst));
             }
        }
        (v, graph)
    });`

However, I am getting this error: 
`error[E0283]: type annotations required: cannot resolve '_: timely::progress::Timestamp'`
  `--> examples/updates.rs:34:41`
`      |`
`34 |         let (edgeArray, graph) = worker.dataflow(|scope| {`
`      |                                                              ^^^^^^^^`
(Arrows are pointing under `dataflow`)

Any ideas why? Thank you!

**Comment by florianre** [comment]
So what's the difference between my code and the one in [https://github.com/frankmcsherry/differential-dataflow/blob/master/examples/degrees.rs](url) on line 27? What does it not need explicit typing?

**Comment by frankmcsherry** [comment]
On line 58 it has

```rust
input.advance_to(1u64);
```

which informs Rust about the type of the timestamps (`u64`).
