### ISSUE TITLE
Off-by-one error in the book examples

### ISSUE THREAD

**Issue by sscdotopen** [TimelyDataflow/differential-dataflow#119]
The example at https://github.com/frankmcsherry/differential-dataflow/blob/master/mdbook/src/chapter_0/chapter_0_1.md has an off-by-one error.

The code feeding the edges must be changed from `input.insert((person/2, person));` to `input.insert((person/2, person + 1));` to correctly produce the skip level outputs for a binary tree with root 0.

**Comment by frankmcsherry** [comment]
I'm not sure I see the bug. The self-loop is intentional, if that is what you mean.

**Comment by sscdotopen** [comment]
Shouldn't the input edges be:
```
(0, 1)
(0, 2)
(1, 3)
(1, 4)
...
```
such that `0` is the skip-level manager of `3` and `4` ?

**Comment by sscdotopen** [comment]
Ah, I got the idea now, its not an error, its just a "weird" tree :) I found the example a little confusing because I was expecting a tree like the one on the left side here, but the actual tree in use is the one on the right side (correct me if I'm wrong). That one makes the example a little difficult to understand because now 0 and 1 actually have a skip-level relationship although they are direct neighbors.  

![](https://i.imgur.com/xdO92fG.png)
