### ISSUE TITLE
does `.leave()` return a distinct collection?

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#129]
This is probably obvious, but let me double-check anyway: when I extract a collection from a recursive fragment of a dataflow graph using `variable.leave()`, the collection I get back is guaranteed to only have distinct records, correct? I know that the fixed point computation inside the loop uses `distinct` to ensure convergence, but I want to be sure that, e.g., the very last iteration does not add non-distinct records.

Thanks!

**Comment by frankmcsherry** [comment]
Absolutely *not* guaranteed to be distinct. Bear in mind that distinctness is an idiom in differential dataflow, which hosts much more general collections (in your case, multisets). If your iterative computation derives multiple instances of a fact, then the collection that results from `leave` should be identical to its limit (value in the last iteration), with no duplicate suppression or other logic applied to it.

The `leave` operation is essentially just a record-to-record transformation that removes the inner timestamp, removing the distinctions of changes that occur at a finer granularity than the outer scope understands. It logically corresponds to returning the "final" collection in the iterative scope.

**Comment by ryzhyk** [comment]
Apologies, I should have been more specific: I am specifically wondering about recursive collections built using the `Variable` type that I plagiarized from one of your examples (which I don't think any longer exists):

```
pub struct Variable<'a, G: Scope, D: Default+Data+Hashable>
where G::Timestamp: Lattice+Ord {
    feedback: Option<Handle<Product<G::Timestamp, u32>, (D, Product<G::Timestamp, u32>, isize)>>,
    current: Collection<Child<'a, G, Product<G::Timestamp, u32>>, D>,
    cycle: Collection<Child<'a, G, Product<G::Timestamp, u32>>, D>,
    name: String
}
...
```

My understanding was that the `distinct()` call in the `drop()` method below takes whatever the iterative computation produces and makes it distinct, and hence the resulting collection is also distinct. Am I correct or am I still missing the point?

```
impl<'a, G: Scope, D: Default+Data+Hashable> Drop for Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    fn drop(&mut self) {
        if let Some(feedback) = self.feedback.take() {
            with_prof_context(
                &self.name,
                ||self.current.distinct()
                            .inner
                            .map(|(x,t,d)| (x, Product::new(t.outer, t.inner+1), d))
                            .connect_loop(feedback));
        }
    }
}
```

**Comment by frankmcsherry** [comment]
Ah, we should check out all of the code. The `distinct()` will ensure that the changes in subsequent rounds are those experienced by the distinct collection, but it will be important to sort out exactly which thing you are calling `leave()` on; it is not the collection just after the `distinct()` up above, which means it could possibly be something different.

If the `Variable` is initially empty, then I think calling `leave()` on it should be fine. If not initially empty, then the feedback loop could add distinct values to the pre-existing collection, which might not be distinct. I'm pretty sure we can make something that works for you, though.

Should we perhaps add a `DistinctVariable` in to the differential codebase, alleviating you of the responsibility of understanding all of this weird stuff? :D

**Comment by ryzhyk** [comment]
I am calling `leave()` on the `self.cycle` thing returned by `deref()`. Here is a complete implementation:
```
/// A collection defined by multiple mutually recursive rules.
///
/// A `Variable` names a collection that may be used in mutually recursive rules. This implementation
/// is like the `Variable` defined in `iterate.rs` optimized for Datalog rules: it supports repeated
/// addition of collections, and a final `distinct` operator applied before connecting the definition.
pub struct Variable<'a, G: Scope, D: Default+Data+Hashable>
where G::Timestamp: Lattice+Ord {
    feedback: Option<Handle<Product<G::Timestamp, u32>, (D, Product<G::Timestamp, u32>, isize)>>,
    current: Collection<Child<'a, G, Product<G::Timestamp, u32>>, D>,
    cycle: Collection<Child<'a, G, Product<G::Timestamp, u32>>, D>,
    name: String
}

impl<'a, G: Scope, D: Default+Data+Hashable> Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    /// Creates a new `Variable` from a supplied `source` stream.

    pub fn from(source: &Collection<Child<'a, G, Product<G::Timestamp, u32>>, D>, name: &str) -> Variable<'a, G, D> {
        let (feedback, cycle) = source.inner.scope().loop_variable(1);
        let cycle_col = Collection::new(cycle);
        let mut result = Variable { feedback: Some(feedback), current: cycle_col.clone().filter(|_| false), cycle: cycle_col, name: name.to_string() };
        result.add(source);
        result
    }

    /// Adds a new source of data to the `Variable`.
    pub fn add(&mut self, source: &Collection<Child<'a, G, Product<G::Timestamp,u32>>, D>) {
        self.current = self.current.concat(source);
    }
}

impl<'a, G: Scope, D: Default+Data+Hashable> ::std::ops::Deref for Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    type Target = Collection<Child<'a, G, Product<G::Timestamp,u32>>, D>;
    fn deref(&self) -> &Self::Target {
        &self.cycle
    }
}

impl<'a, G: Scope, D: Default+Data+Hashable> Drop for Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    fn drop(&mut self) {
        if let Some(feedback) = self.feedback.take() {
            with_prof_context(
                &self.name,
                ||self.current.distinct()
                            .inner
                            .map(|(x,t,d)| (x, Product::new(t.outer, t.inner+1), d))
                            .connect_loop(feedback));
        }
    }
}
```

I think the variable is initially empty, i.e., I create `new_collection()` in the outer scope and then immediately `enter()` it into the inner scope, without `concat`'ing anything to it. 

I actually think that at least `Variable` (but `DistinctVariable` as well, possibly) would be really nice to have in the DD codebase. I realize it is only a convenience API, but it is hard for most DD users (like myself) to come up with this code without your help.

**Comment by frankmcsherry** [comment]
[`Variable`](https://github.com/TimelyDataflow/differential-dataflow/blob/master/src/operators/iterate.rs#L141-L147) does exist in the codebase, just not the `DistinctVariable` or `MonotonicVariable` variants. 

It is bedtime where I am now, but I'll try and take a look in the coming days. My quick scan suggests that it should be distinct, as even though `source` may be non-empty, the `cycle` member is initially empty. I'll also try and figure out if we can use differential's `Variable` to make this easier for you.

**Comment by frankmcsherry** [comment]
apropos using differential's `Variable`: what is `with_prof_context` and is it crucially important?

**Comment by ryzhyk** [comment]
> apropos using differential's `Variable`: what is `with_prof_context` and is it crucially important?

It's just my profiling code and is not important.

**Comment by ryzhyk** [comment]
> [`Variable`](https://github.com/TimelyDataflow/differential-dataflow/blob/master/src/operators/iterate.rs#L141-L147) does exist in the codebase, just not the `DistinctVariable` or `MonotonicVariable` variants.

That's what I meant. The naming is unfortunate: my `Variable` is your `MonotonicVariable` (I think), not `iterate::Vareiable`.

> It is bedtime where I am now, but I'll try and take a look in the coming days. My quick scan suggests that it should be distinct, as even though `source` may be non-empty, the `cycle` member is initially empty. I'll also try and figure out if we can use differential's `Variable` to make this easier for you.

That would be really helpful, thanks heaps!

**Comment by frankmcsherry** [comment]
Btw, I am now recalling that the reason we don't have you using a differential `Variable` is that your bespoke one avoids some self-inflicted memory requirements. The naive implementation derives each fact at least twice, i. the initial derivation and ii. the cycled-back-around derivation. The version you have avoids this.

But, probably still a smart thing to add to the core library!

**Comment by frankmcsherry** [comment]
I think this is analogous to #189, which is also now closed (the issue being communication, rather than technical).
