### ISSUE TITLE
Not able to run the capture_recv example

### ISSUE THREAD

**Issue by tsk70** [TimelyDataflow/differential-dataflow#144]
I am getting the below error while running the capture_recv example. 
>>
cargo run --example capture_recv
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/capture_recv`
thread 'worker thread 0' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by frankmcsherry** [comment]
Is it possible that this should be in the `timely-dataflow` repository?

If so, the `capture_recv` example there has [arguments that must be supplied](https://github.com/TimelyDataflow/timely-dataflow/blob/master/examples/capture_recv.rs#L10). Specifically, you need to indicate the number of source workers that the computation should expect to find.

**Comment by tsk70** [comment]
Thanks @frankmcsherry for the quick response. It my bad that I didn't pass the workers and filed the issue in this repo instead of timely-dataflow.
