### ISSUE TITLE
Working with multi-dimensional updates

### ISSUE THREAD

**Issue by sdht0** [TimelyDataflow/differential-dataflow#222]
I have is a set of N dimensional updates whose partially orders wrt to each other are known. I want to tell DD to process these updates according to their partial orders.

I've been using `unordered_input::UnorderedInput` along with a custom timestamp struct and assigning a timestamp to each set of updates in a way that the partial orders are maintained.

The issue is, my current timestamp struct is a `Vec<u32>`, to handle partial orders in an arbitrary number of dimensions.  But these `Vec` timestamps is leading to a 5x hit in total runtime performance (comparing `Vec<u32>` of len 1 with simple `u32`, pagerank on 34M edge graph). I'm now considering encoding the partial orders in a single u128 that will handle a limited number of dimensions.

But I wanted to ask you if there is a better way to tell DD about updates in an arbitrary number of dimensions. Say there is the initial set of edges `E` and `n` updates `U1`, `U2`, .. `Un`, I want DD to process every `Ui` as an update to `E` only. In terms of timestamps, if `E = (0, 0, 0, ...)`, then `U1 = (1, 0, 0, ..)`, `U2 = (0, 1, 0, ..)`, and so on. Here, `n` could be arbitrarily large.

**Comment by frankmcsherry** [comment]
If the updates aren't meant to interact, you might want an enum rather than a vector. I can't tell from the description here what the intent is, though!

**Comment by sdht0** [comment]
No, the updates do interact. My example was on the extreme end.

So let's say we have an initial set of edges E and updates (additions and deletions) {U1, U2, ...} to these edges arranged in 2 dimensions. Say we can organize these in the shape of a 2x3 grid:
```
   0   1   2
  ------------
0 | E   U1  U2
1 | U3  U4  U5
```
The grid indicates the partial orders between the updates, so e.g., U4 is an update to the combined graph of {E, U1, U3}.

What I do right now is assign these a 2D vector timestamps, so `E = (0,0)`, `U1 = (0,1)`, `U3 = (1,0)`, and so on, using my Vec<u32> struct and  `unordered_input::UnorderedInput` and DD understands the order dependencies from these. Not the conventional way to use DD for sure.

**Comment by frankmcsherry** [comment]
Okies. I don't understand the question, then. Having more general timestamps will impact performance. In the case above this could be a `(usize, usize)`, but if you would like the generality of an unbounded (at compile time) vector then this may cost in terms of runtime.

Are there parts of the code that you think could be more responsible about timestamp manipulation that are expensive when one uses heap-allocated timestamps? Or, is that the question?

**Comment by sdht0** [comment]
Sorry for the long haitus. I also see that I bundled 2 questions into 1.

So for the first part, yes I do want a general vector, like the one defined in the [multitemporal experiment](https://github.com/TimelyDataflow/differential-dataflow/blob/master/experiments/src/bin/multitemporal.rs#L257). My question was more of a verification that DD does not have another magical way to order things. The answers looks to be in the negative.

> Having more general timestamps will impact performance
Right, and I suppose its mainly because of the `less_than` call for each timestamp generated in the iterations. I am now thinking if there is a smart caching that can be done to avoid the vector accesses. 

The second part is: is there a way to run DD computations such that it gets an initial input at say time t, applies a linear set of updates at times `t1`, `t2`, `t3`, ..., then somehow "reverts" back to time t (without actually negating the updates in t*) and applies another set of updates `w1`, `w2`, `w3`, ..., where there is no order between `w*` and `t*`. So essentially a way to "save" the initial input and perhaps perform the rest of the updates in different _scopes_ that are independent of each other. I'd want to do this `n` times at runtime, so want to avoid defining n-dimensional timestamps. The answer is again probably in the negative.

**Comment by sdht0** [comment]
Closing this for now. The answer to my question is as you mentioned: supporting n-tuple `UnderOrderedInput` will need a dynamic data structure like a vector and will incur the equivalent runtime cost.
