### ISSUE TITLE
the trait bound `G: timely::dataflow::scopes::Scope` is not satisfied(E0277)

### ISSUE THREAD

**Issue by top1select** [TimelyDataflow/differential-dataflow#229]
After updating differential-dataflow from "0.10" to "0.11", all functions are starting to have this error,
e.g. in the graphs-static file, the reach, bfs and connected_components functions

`error[E0277]: the trait bound `G: timely::dataflow::scopes::Scope` is not satisfied
   --> tests/graph-static.rs:180:1
    |
180 | / fn connected_components<G: Scope<Timestamp = ()>>(
181 | |     scope: &mut G,
182 | |     forward: &mut TraceHandle,
183 | |     reverse: &mut TraceHandle,
...   |
222 | |     })
223 | | }
    | |_^ the trait `timely::dataflow::scopes::Scope` is not implemented for `G`
    |
    = help: consider adding a `where G: timely::dataflow::scopes::Scope` bound
    = note: required by `differential_dataflow::Collection``

Please advise.

**Comment by frankmcsherry** [comment]
Type `cargo update`.

**Comment by top1select** [comment]
Tried cargo update, still the same, is it because I actually put these file/code blocks under the "tests" folder, and I'm using #[test] to run them as tests?

**Comment by frankmcsherry** [comment]
Can you say more about what you are doing? Differential master builds fine for me. Which commands are you typing?

**Comment by top1select** [comment]
I'm using Visual Studio Code, and put all of the examples and experiments under the "tests" folder, and put the #[test] in front of the function call, which is "graphs_test", then VSC automatically generated the "Run Test" button, and the underlying command seems to be below:

Executing task: cargo test -- --nocapture graphs_test <

**Comment by frankmcsherry** [comment]
The error you are seeing is Rust's way of saying "you aren't using the right version of timely", which most likely means that somewhere there is a 0.10 timely dependency written down. If you have that in your Cargo.toml, change it to 0.11.

**Comment by top1select** [comment]
It worked, thanks!
