### ISSUE TITLE
What's the recommended IDE to develop DD applications?

### ISSUE THREAD

**Issue by top1select** [TimelyDataflow/differential-dataflow#232]
What's the best way to understand the syntax of DD high level operators, map, reduce etc as below:

// if (m2, m1) and (m1, p), then output (m1, m2, p)
                manages
                    .map(|(m2, m1)| (m1, m2))
                    .join(&manages)

> This program has a bit of boilerplate, but at its heart it defines a new input manages and then joins it with itself, once the fields have been re-ordered

So what's the join rules, what's the ordering rules and what's the syntax sugar of input[0].0, in below?

// report the smallest value for each group
    ///         scope.new_collection_from(1 .. 10).1
    ///              .map(|x| (x / 3, x))
    ///              .reduce(|_key, input, output| {
    ///                  output.push((*input[0].0, 1))
    ///              });

Is there a recommended IDE to develop DD app? Like when developing Spark/Scala in IntelliJ Idea, there are a lot of hints about the RDD transformers, and the data structures within the transformed RDDs.

P.S. I came from Java/Scala/Spark background, and I find it really hard to understand and follow the DD examples, although I am able to figure out the graph problems and algorithms, I don't quite understand the DD operators, especially the lambda expressions.

**Comment by frankmcsherry** [comment]
You should be able to use any IDE that supports Rust, or even a text editor. I personally use VS Code, though I have used Sublime in the past. CLion also has good support for Rust.

To learn about differential dataflow, I would read through the mdbook and the documentation, which are linked from the `README.md` in the root of the project. The `reduce` operator, for example, has its own section where it is detailed.
