### ISSUE TITLE
How to handle float data type?

### ISSUE THREAD

**Issue by top1select** [TimelyDataflow/differential-dataflow#233]
In abomonation, there are f32 and f64, but still got below error:

the trait `std::cmp::Ord` is not implemented for `f32`
   |
   = note: required because of the requirements on the impl of `std::cmp::Ord` for `(u32, u32, f32)`
   = note: required because of the requirements on the impl of `differential_dataflow::Data` for `(u32, u32, f32)`

What's the best way to deal with float data type?

**Comment by frankmcsherry** [comment]
There are crates for wrapping floats in a false total order (one which equates `NaN`, primarily). One popular one is: https://crates.io/crates/ordered-float
