### ISSUE TITLE
Possible bug in dogs^3

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#234]
I ran into a potential bug in dogs^3, where the output of a program changes with the number of workers:

The repro is here, including a detailed description in the commit message:
https://github.com/ryzhyk/differential-dataflow/tree/dogs_bug

**Comment by ryzhyk** [comment]
@frankmcsherry, just wondering if you still plan to look into this at some point. There is no rush, but delta queries are really nice. We'd love to be able to eventually use them in DDlog, and I bet many other DD users feel the same way :)

Thanks,
Leonid

**Comment by frankmcsherry** [comment]
Investigating! Thank you for the easy reproduction!

**Comment by frankmcsherry** [comment]
I have a PR up that requires arrangement's `enter_at` method to take a timestamp "inverting" method that walks back timestamps to those of the outer scope, which is used to communicate frontier information back up. It would be neat for this to be automatic, but I don't see a way for that to work at the moment.

In the case of `validedges.rs` the change would be something like
```rust
let nodes_arr_alt = nodes_arr.enter_at(inner, |_,_,t|AltNeu::alt(t.clone()), |t| t.time.saturating_sub(1));
let nodes_arr_neu = nodes_arr.enter_at(inner, |_,_,t|AltNeu::neu(t.clone()), |t| t.time.saturating_sub(1));

let edges_arr1_alt = edges_arr1.enter_at(inner, |_,_,t|AltNeu::alt(t.clone()), |t| t.time.saturating_sub(1));
let edges_arr2_alt = edges_arr2.enter_at(inner, |_,_,t|AltNeu::alt(t.clone()), |t| t.time.saturating_sub(1));
```
whose additional method says that we should try and subtract one from each time, unless we are at the minimum element in which case no worries (and don't wrap please).

With this fix, the specific erroneous behavior vanishes for me (I think; a further reduced error case vanishes). It is definitely a bug, and this definitely fixes a bug, but there could be new ones now. :)

**Comment by ryzhyk** [comment]
Thanks for the fix!  I will test the PR with the DDlog branch that knows how to use dogs^3 using several of our datasets and will report back on how that goes.

Do you know by any chance if #235 is a separate problem or another manifestation of this?

**Comment by frankmcsherry** [comment]
No clue yet.

**Comment by ryzhyk** [comment]
Results so far: 

- DDlog delta query tests that used to fail are now passing!! More testing is in progress.
- Unfortunately, #235 has not been magically resolved by this fix :(

Thanks again for looking into these issues!

**Comment by frankmcsherry** [comment]
Cool; I'll merge it and start to look into the leak!
