### ISSUE TITLE
How to split a stream - ie handle success/error differently

### ISSUE THREAD

**Issue by gregberns** [TimelyDataflow/differential-dataflow#248]
Lets say I want to read a file line by line and pass each line in as a message in a stream. Each line can be parsed with a pure function + `map`, but will result in something like `Result<ParsedOutput, ParseError>`.

I want the successfully parsed items to go into one Kafka topic, and the errors to be handled differently (maybe in Kafka or to a file our something). I found the Capture and Replay and Kafka example, but how to I split into two streams?

There's `join` to merge streams, but  I don't see operators like the Haskell `partition` function to split them (just guessing this might be a way to model it).

I'm still trying to figure out how to use dataflow, so forgive me for using it where maybe something like rayon might be used. But, I think its way cooler and will be very helpful the more I understand it, especially for the streaming work we're going to be doing soon.

**Comment by gregberns** [comment]
Thought I found it, but no. There is the `partition` trait in timely, but it requires that the output partitions to be the same type: `(a -> (i, a)) -> [a] -> [[a]]` (not sure thats precise, but kinda close)

So need something like: `((a,b)-> bool) -> [(a,b)] -> ([a],[b])` (this might be close)

https://docs.rs/timely/0.11.1/timely/dataflow/operators/partition/trait.Partition.html

**Comment by frankmcsherry** [comment]
Check out timely's `Branch` trait in [`branch.rs`](https://github.com/TimelyDataflow/timely-dataflow/blob/master/timely/src/dataflow/operators/branch.rs). More generally, you can use timely's  operator builders to de-multiplex streams of more complicated variants, and [demonstrated here](https://github.com/strymon-system/megaphone/blob/master/nexmark/src/bin/timely.rs#L147-L179) in the Strymon project.

Hope this helps.

**Comment by gregberns** [comment]
`branch` did it, thanks Frank.
