### ISSUE TITLE
How to run experiments from your paper

### ISSUE THREAD

**Issue by pradeep-k** [TimelyDataflow/differential-dataflow#258]
Hi,

I am able to run some basic  example that you listed in https://timelydataflow.github.io/differential-dataflow/, but can't really run CC that you demonstrated in the differential dataflow paper. I am not even a beginner in rust. 

I need to run some graph algorithms such as connected components (CC), BFS, etc when the data is hosted in a file (or files). If you can provide the ready to use commands, with configurable batch size,  file format that hosts data, and how that will be treated as stream source, I will really appreciate your help. 

What all known graph algorithms do you support out of the box? 
Do you support weighted graphs?
Do you support arbitrary weight data structure?

Purpose: These results will be used in a research paper that I am writing. Your help will be acknowledged. Thanks.

**Comment by frankmcsherry** [comment]
Hi!

Thanks for the interest. Unfortunately, this is not a service I currently offer. I recommend learning Rust; it's a great language for systems programming.

Good luck!

**Comment by pradeep-k** [comment]
Thanks for your response. Can you answer these questions that I asked earlier:
What all known graph algorithms do you support out of the box? Please name a few, it will be sufficient for me.
Do you support weighted graphs?
Do you support arbitrary weight data structure?
