### ISSUE TITLE
Reusing arrangements in iterations

### ISSUE THREAD

**Issue by sdht0** [TimelyDataflow/differential-dataflow#293]
Hi!

Consider the following iterative dataflow to implement SSSP:
```rust
type Distance = u32;
type Node = u32;
type Edge = (Node, (Node, Distance));

fn sssp<G: Scope>(
    edges: &Collection<G, Edge>,
    roots: &Collection<G, (Node, Distance)>,
) -> Collection<G, (Node, Distance)>
where
    G::Timestamp: Lattice + Ord,
{
    roots.iterate(|inner| {
        let edges = edges.enter(&inner.scope());
        let roots = roots.enter(&inner.scope());

        inner
            .join_map(&edges, |_k, l, d| (d.0, l + d.1))
            .concat(&roots)
            .reduce(|_, s, t| t.push((*s[0].0, 1)))
    })
}
```
This dataflow is maintaining 4 arrangements: 2 for the left (distances) and right (edges) of `join_map` and 2 for the input and output of `reduce`. But note that the output of `reduce` is the left input to `join_map`, which means the same collection is being arranged twice. I was wondering if this duplication can be avoided by sharing the arrangement or if it is inherent to how iterations work in DD that prevents sharing around iterations. At the very least, the `iterate` and `Variable` operators all seem to be working with Collections. Is it possible to write an `Arranged<>`-based iterative operator, where the output of the iteration becomes a shared input to the loop? It feels possible to be able to modify the `Variable` implementation to work with an `arranged` member instead of than the current `collection`, however I'm finding it difficult to write a generic `Arranged` data type.

On a related note, I'm still wrapping my head around the details of the operator implementations. When you have some free time, it'd be great if you could make a video explaining the hairy details of the DD operators, especially `reduce` and `iterate`. For example, the doc for `Variable` mentions it can be used when `requiring more sophisticated iterative patterns than singly recursive iteration`. Perhaps you can talk about the differences and demonstrate examples of  `mutual recursion [where] two collections evolve simultaneously`? Just a thought.

**Comment by frankmcsherry** [comment]
I might have mis-understood the example, but you can certainly share the arrangements by pivoting the iteration. Instead of doing join, concat, reduce, you can do concat, reduce, join. Typically you would need to avoid `iterate` and directly construct a scope and a `iterate::Variable` though.

Let me see if I can track down an existing example of this pattern. Practically, it often doesn't buy too much in graph processing, because the node state is so much smaller than the edge state.

**Comment by frankmcsherry** [comment]
For example, https://github.com/TimelyDataflow/differential-dataflow/blob/master/experiments/src/bin/graspan2.rs has several instances of the "create a variable, arrange it, re-use it". It's not the example you've mentioned above, but it should get you started on implementing that.

**Comment by sdht0** [comment]
> you can do concat, reduce, join
Ah I see, didn't even think about reordering the operators!

> directly construct a scope and a iterate::Variable
I was thinking in these lines, but aren't the input and output of `Variable` Collections?

Thanks for the grapspan2 example, I'll take a look.

**Comment by frankmcsherry** [comment]
Yes, the `Variable` is for collections, but if you think of your dependencies as a cyclic graph, you just need to put some `Variable`s in to break all the cycles. You can choose to put them anywhere, though, including not where an arrangement is (e.g. the output of a join).

**Comment by sdht0** [comment]
I see. I don't understand `Variable` enough yet, but I'll go through the existing uses.

Thanks for the help!
