### ISSUE TITLE
Streaming analytics with DD.

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#294]
I would like to compute a join of two collections `A(x,z) :- B(x,y), C(y,z).`, where `B` is a regular database table that does not change from timestamp to timestamp, unless explicitly modified by an `insert` or `delete`, whereas `C` behaves as an ephemeral stream: the user inserts some values into `C` on each timestamp.  These value disappear at the next timestamp.

I can of course implement this by deleting all previously inserted values from `C` before feeding new data for each timestamp, but this seems like an inefficient way to go about it, as we will essentially compute on each value twice, when inserting and deleting it, not to mention the overhead of building and tearing down the arrangement of `C` on each timestamp.

So I am looking for a better way to join ephemeral streams with persistent collections.  It appears that [`lookup_map`](https://github.com/TimelyDataflow/differential-dataflow/blob/master/dogsdogsdogs/src/operators/lookup_map.rs) in `dogs^3` does exactly that: joins an arrangement with a set of changes to the `prefixes` collection. I know that this operator mostly exists to support the WCOJ use case, but am I correct that it can be used in this situation? If not, is there another way to do this type of stream analytics?

Thanks!

**Comment by frankmcsherry** [comment]
You should be able to use `lookup` and variants for this. The main caveat is that you are breaking from DD orthodoxy at that point, and while the results do have correct/incorrect behavior, it's up to you to make sure that you use them correctly. For example, `lookup` should never produce output changes in response to its arranged inputs (as the other input is ephemeral), so if you ever want that you'll need to set up some other dataflow for it.

But yup. This is what `dogs^3` does internally, because it has the same ephemeral streams. Just, there's also some work in there to make sure that it's used correctly, and the wiring up could be done incorrectly.

**Comment by frankmcsherry** [comment]
The other caveat is that the `dogs^3` construction only works for totally ordered times, so it's especially complicated if you want to use `lookup` in an iterative context (which .. I'm guessing could be relevant).

**Comment by ryzhyk** [comment]
Right, I understand that this won't work with recursion.  We should also avoid arranging the output of such an ephemeral join, or the arrangement will grow unboundedly.

> For example, lookup should never produce output changes in response to changes in its arranged inputs (as the other input is ephemeral)

Could you please clarify this?  My mental model was that `lookup_map` will match each record from the ephemeral stream against the contents of the arrangement at the present timestamp, so that whatever changes happen to the arrangement during this timestamp will be reflected in the output of `lookup_map`.  Is the actual invariant more subtle than that?

**Comment by frankmcsherry** [comment]
Yeah, sorry I only meant that .. if you start to apply arbitrary changes to the arranged input, nothing actually comes out of the dataflow until you provide another ephemeral probe. That's the main part that's a bit of a break with DD: the input changed, but the output does not change.

**Comment by ryzhyk** [comment]
Understood, thanks a lot for the explanation!  I am going to try it out.

**Comment by ryzhyk** [comment]
Yes, it works really well. Using `lookup_map` for streaming joins is 2x-3x faster than trying to solve this using regular arranged joins and deleting old inputs at each iteration. Thanks again for helping out!
