### ISSUE TITLE
Streaming arrangement.

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#303]
I would like to create an arrangement containing only changes to a collection introduced during the current timestamp.  I think I can do this by retracting the previous contents of the collection:

```
c.concat(c.delay(1).negate()).arrange_by_key()
```

I wonder if there's a more direct or more efficient way.

Thanks!

**Comment by frankmcsherry** [comment]
That may do a thing. I think at some point you may just want to pick up writing your own timely operators, as they may get you what you need more directly. I'm off for a week+ on vacation; apologies for any unavailability!
