### ISSUE TITLE
Strategies for maintaining persistent states (the data in Collections)

### ISSUE THREAD

**Issue by AshleySchaeffer** [TimelyDataflow/differential-dataflow#350]
Before I start, apologies if this is covered somewhere or I've misunderstood some of the concepts surrounding my problem. I've read most of the documentation and I think I have a reasonable understanding of what's going on in Collections and Streams. I've searched through issues for both timely and differential dataflow and only found one issue which concludes that all data must be replayed in order to restablish a lost state.

While I don't think it's managed natively within Differential, I have been trying to brain storm ways in which one could maintain a persistent state of collections in or near real-time. I.e. to store collections to disk or make a representive copy of the data in a key value store (e.g. RocksDB). I thought I may be able to use traces to get access to the underlying data within collections (I could well be misunderstanding traces here) with the plan being to make a copy of the data elsewhere, however I'd rather not deal with the [responsibilities](https://timelydataflow.github.io/differential-dataflow/chapter_5/chapter_5_3.html?highlight=trace#great-responsibility) involved in handling a TraceHandle.

I have also considered just using operators themselves to store states based on a received collection, but I can't see how that would work across distributed nodes, which lead me to considering using a network accessible key value store as a sort of centralized store of states. 

I've read the [capture and replay](https://timelydataflow.github.io/timely-dataflow/chapter_4/chapter_4_4.html?search=) section in the docs and while it makes sense, I'd rather avoid storing data that has already been processed once and I don't know how you would avoid the output at the end of a computation poluting downstream services with replicas of computation outputs that have historically already been seen.

Besides constructing a representive copy of a state, I'm not sure how one would go about reconstructing one for each operators corresponding collection. I keep ending up with concluding that I must replay data, which I'm not sure is an option given the volumes I'll be dealing with and it seems a bit redundant to have to store all data fed into a computation when I only care about the statistics and outcomes generated by computations.

I feel I'm about at the stage where I reluctantly have to write off using Differential as my use case requires that states persist upon node failures so that the system may resume computations from where it left off. I noticed Materialize (which uses this library) is aiming to support persistence in this way, but I don't know if this will be added by way of this library or it will be added into Materialize as an addon.

I think this is the right place to ask given that Timely doesn't feel like the place for persistent states to exist. I must say I really was a bit mind blown by Timely and Differential, they introduce a new paradigm to me that I've not considered before and I think it's fantastic that it's out there in the open source community. Thank you!

Anyway, Is there any suggested and reliable work around people have used or can think of for persisting and restablishing state?

**Comment by frankmcsherry** [comment]
Hi! Sorry for the delayed response.

Differential dataflow is best thought of as a *compute* layer. It's not a database, and doesn't maintain any persistent storage for you. You are right that Materialize is looking to do that, among other things. The strategy there, and what I would recommend generally, is to use your tool of choice (several folks already have preferences) to maintain your source-of-truth input data, and flow it in to the DD computations that you require. DD won't keep a second copy of your data, other than what it needs to maintain its computations (e.g., counts if you are counting things, indexed rows if you are joining things).

I hope this helps!

**Comment by AshleySchaeffer** [comment]
It does help thank you! I think architecturally I'm trying to use Differential in the wrong way so I'm going back to the drawing board on the whole. Oddly came upon some stuff today that made me question my use of it but you have confirmed. Thanks again.
